### ISSUE TITLE
Comments are off by 1 line

### ISSUE THREAD

**Issue by gersmann** [jordemort/action-pyright#25]
It seems like comments are generally off by 1 line, e.g.
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2694872/158846492-834c5b32-cd7a-49cf-abc9-979986290446.png">

This affects all test comments I have generated.

**Comment by gersmann** [comment]
> I think @Chadsr ran into this too - maybe we just need to add in an offset in pyright_to_rdjson.py?

Yeah, linenumber + 1 it seems?

**Comment by jordemort** [comment]
@gersmann I think it's probably a bug that's affecting everyone that uses it. I want to play around with it a bit to confirm, but I'm on the road this week - I might not get time to mess with it until next week. PRs are always welcome, of course ;)

**Comment by Chadsr** [comment]
I had intended to extend the unit test to catch this, but I did not fully get around to confirming it. (and i'm also a bit too busy right now)

Ideally the unit test should have an example output from Pyright to check against the generated rdjson output. If the test still passes, then somehow the line numbers must be getting jumbled further on in the pipeline?

**Comment by gersmann** [comment]
https://github.com/microsoft/pyright/issues/3238

**Comment by gersmann** [comment]
So the pyright team confirmed, their offsets are 'zero-based', which means that we should be able to safely increase those by offset 1.

**Comment by jordemort** [comment]
Fixed in https://github.com/jordemort/action-pyright/pull/26
