### ISSUE TITLE
pyright installation installs all node dependencies

### ISSUE THREAD

**Issue by rnovacek** [jordemort/action-pyright#33]
The action runs `npm install pyright` [here](https://github.com/jordemort/action-pyright/blob/main/script.sh#L19) (or similar when specific pyright version is specified). This means all node dependencies are installed as well if `package.json` exists in the repo as well. I don't think it's necessary and it slows down the check significantly. 

It might be better to use `npx`/`npm exec` to install and run directly in one command.

**Comment by jordemort** [comment]
This is a good idea; I'll get around to implementing it eventually but would happily accept a pull request if you don't want to wait :)

**Comment by jordemort** [comment]
Implemented in https://github.com/jordemort/action-pyright/pull/34 - thanks for the idea!

**Comment by rnovacek** [comment]
Thank you for the improvement!
